### ISSUE TITLE
На ESP32S2 (LOLIN MINI S2) не могу запустить Blinker

### ISSUE THREAD

**Issue by lgadina** [MoonFox2006/ESP32_BlinkerButtons#1]
#include "Blinker.h"

Blinker blinker(15, LOW);

void setup() {
  blinker = Blinker::BLINK_2HZ;
}

void loop() {
}

Никакой реакции от светодиода :(

**Comment by MoonFox2006** [comment]
В конструкторе класса Blinker создается объект таймера, но на момент вызова конструктора FreeRTOS еще не проинициализирована полностью. Т.е. нужно отложить создание объекта, создав его в динамической памяти.

`...
Blinker *blinker;

void setup() {
  blinker = new Blinker(15, HIGH);
  *blinker = Blinker::BLINK_2HZ;
}
...`

**Comment by lgadina** [comment]
Вот жеж... Спасибо!
